function cellType = bc_classifyStriatalCells(qMetric, ephysProp)
    cellType = struct; 
    % get good units 
goodUnits = qMetric.numSpikes >= param.minNumSpikes & qMetric.waveformRawAmpli >= param.minAmpli & ...
    qMetric.fractionRPVchunk <= param.maxRPV ...
    & qMetric.somatic == param.somaCluster & qMetric.pMissing < param.maxPercMissing;

%classify into 4 groups
cellType.msn = ephysProp.postSpikeSuppression < 40 & ephysProp.templateDuration > param.cellTypeDuration;
cellType.fsi = ephysProp.prop_long_isi < 0.1 & ...
    ephysProp.postSpikeSuppression < param.cellTypePostS & ...
    ephysProp.templateDuration < param.cellTypeDuration;
cellType.tan = ephysProp.postSpikeSuppression >= 40 & ephysProp.templateDuration > param.cellTypeDuration;
cellType.uin = ephysProp.prop_long_isi > 0.1 & ...
    ephysProp.postSpikeSuppression < param.cellTypePostS & ...
    ephysProp.templateDuration < param.cellTypeDuration;
end